import os
import glob

# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"

# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/seqkit_stats/barcode_classification_table.txt",
        "results/flag_files/create_output_reads_dir.done"
    default_target: True


# merge raw demultiplexed basecalled reads
# -----------------------------------------------------

rule merge_reads:
    """
    Concatenate the original demultiplexed reads from the sequencing run(s).
    Combines the fastq for each barcode and unclassified reads into a single fastq
    Supports merging across multiple run directories (e.g. interrupted + resumed run)
    """
    output:
        "results/merged_reads/merged_reads.fastq"
    message:
        """--- Concatenating original demultiplexed reads."""
    params:
        reads_dirs = config["reads_dirs"]
    log:
        "logs/merge_reads/merge_reads.log"
    benchmark:
        "benchmarks/merge_reads/merge_reads.benchmark.txt"
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        """
        # load seqkit
        module load Miniforge3/24.1.2-0
        eval "$(conda shell.bash hook)"
        conda activate seqkit

        # concatenate with seqkit scat and remove any duplicate reads with rmdup
        (seqkit scat -j {threads} -f {params.reads_dirs} | \
        seqkit rmdup -n -j {threads} -o {output}) 2> {log}
        """

# sample reads (subsample reads to create a test set)
# -----------------------------------------------------

rule sample_reads:
    """
    create a test subsample of merged reads
    """
    input:
        rules.merge_reads.output
    output:
        "results/sample_reads/subsampled_reads.fastq"
    message:
        """--- Subsampling reads."""
    params:
        N = config["sample_reads"]["N"]
    log:
        "logs/sample_reads/sample_reads.log"
    benchmark:
        "benchmarks/sample_reads/sample_reads.benchmark.txt"
    threads: 1
    resources:
        mem_mb = 16000
    shell:
        """
        set +o pipefail;

        # load seqkit
        module load Miniforge3/24.1.2-0
        eval "$(conda shell.bash hook)"
        conda activate seqkit

        # subsample to N reads
        cat {input} \
            | seqkit sample -p 0.1 -s 11 \
            | seqkit head -n {params.N} -o {output}
        """

# demux merged basecalls
# -----------------------------------------------------

rule dorado_demux:
    """
    demux the reads
    """
    input:
        # to test demux on a subsample of reads, use subsampled reads as input:
        # merged_fastq = rules.sample_reads.output
        # to run on full dataset use:
        merged_fastq = rules.merge_reads.output
    output:
        out_dir = directory(lookup(within=config, dpath="dorado_demux/out_dir")),
        flag_file = touch("results/flag_files/dorado_demux.done")
    message:
        """--- Running Dorado Demux."""
    log:
        "logs/dorado_demux/dorado_demux.log"
    benchmark:
        "benchmarks/dorado_demux/dorado_demux.benchmark.txt"
    params:
        kit = lookup(within=config, dpath="dorado_demux/kit_name"),
        out_dir = lookup(within=config, dpath="dorado_demux/out_dir"),
        arrangement = lookup(within=config, dpath="dorado_demux/barcode_arrangement_toml"),
        sequences = lookup(within=config, dpath="dorado_demux/barcode_sequences_fasta")
    threads: 8
    resources:
        mem_mb = 32000
    shell:
        """
        module load dorado

        dorado demux \
            {input.merged_fastq} \
            --verbose \
            --kit-name {params.kit} \
            --threads {threads} \
            --emit-fastq \
            --emit-summary \
            --output-dir {params.out_dir} \
            --no-trim \
            --barcode-arrangement {params.arrangement} \
            --barcode-sequences {params.sequences} 2> {log}
        """

# demux stats with seqkit stats
# -----------------------------------------------------

rule seqkit_stats:
    """
    Run seqkit stats to compute stats on demultiplexed reads
    """
    input:
        demuxed_reads_dir = rules.dorado_demux.output.out_dir,
        dorado_demux_flag_file = rules.dorado_demux.output.flag_file
    output:
        table = "results/seqkit_stats/barcode_classification_table.txt",
        flag_file = touch("results/flag_files/seqkit_stats.done")
    message:
        """--- Computing stats on demuxed files."""
    log:
        "logs/seqkit_stats/seqkit_stats.log"
    benchmark:
        "benchmarks/seqkit_stats/seqkit_stats.benchmark.txt"
    threads: 8
    resources:
        mem_mb = 16000
    shell:
        """
        # load seqkit
        module load Miniforge3/24.1.2-0
        eval "$(conda shell.bash hook)"
        conda activate seqkit

        seqkit stats \
            --threads {threads} \
            --tabular \
            --all \
            --basename \
            {input.demuxed_reads_dir}/*.fastq > {output.table} 2> {log}
        """

# copy demultiplexed fastq(s) for each barcode into own directory
# -----------------------------------------------------

rule create_output_reads_dir:
    """
    copy demultiplexed fastq(s) per barcode into own subdirectory within target output directory
    e.g. copy the fastq(s) for barcodeXX into a subdirectory called barcodeXX
    """
    input:
        dorado_demux_out_dir = rules.dorado_demux.output.out_dir,
        seqkit_stats_flag_file = rules.seqkit_stats.output.flag_file
    output:
        touch("results/flag_files/create_output_reads_dir.done")
    message:
        """--- Creating final output demultiplexed read directory."""
    params:
        out_dir = config["out_dir"]
    shell:
        """
        # create output directory
        mkdir -p {params.out_dir}

        # move reads for each barcode into it's own subdirectory within '{params.out_dir}'
        for fastq in {input.dorado_demux_out_dir}/*barcode*.fastq
        do
            # Extract the barcodeNN part (e.g., barcode01)
            barcode=$(basename "$fastq" | grep -o 'barcode[0-9]\+')

            # Make sure we found a barcode
            if [[ -n "$barcode" ]]; then
                # Create barcode directory inside target_dir
                mkdir -p "{params.out_dir}/$barcode"

                # Copy file into that directory
                cp "$fastq" "{params.out_dir}/$barcode/"

                echo "Copied "$fastq" -> {params.out_dir}/$barcode/"
            else
                echo "WARNING: No barcode found in $fastq"
            fi
        done

        touch {output}
        """


