# path to reads directory/directories containing the fastq pass reads for the sequencing run
reads_dirs:
  - "/well/pharrison/users/piz649/raw_data/bd2_pilot2_sequencing_data/BD2_Capture_pilot_2_300326/BD2_Capture_pilot_2_300326_2/20260331_1407_P2S-03139-A_PBI33122_e36e304a/fastq_pass"
  - "/well/pharrison/users/piz649/raw_data/bd2_pilot2_sequencing_data/BD2_Capture_pilot_2_300326/Pilot_capture2/20260330_1237_P2S-03139-A_PBI33122_3a9c76ff/fastq_pass"

sample_reads:
  N: 1000000

dorado_demux:
  out_dir: "results/dorado_demux"
  kit_name: "NB96Custom" # must match name field in arrangement toml
  barcode_arrangement_toml: "data/barcode_arrangement.toml"
  barcode_sequences_fasta: "data/barcode_sequences.fa"

# Final output directory to place the demultiplexed reads in
# Each barcode fastq output by dorado demux is placed within it's own subdirectory
# within this parent directory
out_dir: "results/output_reads"
